# alt-nvidia-331-cuda-mps-control
# Autogenerated from man page /usr/share/man/man1/alt-nvidia-331-cuda-mps-control.1.gz
# using Type1
complete -c alt-nvidia-331-cuda-mps-control -o uid --description 'Start a new MPS server for the specified user (UID).'

