# archdetect
# Autogenerated from man page /usr/share/man/man1/archdetect.1.gz
# using Darwin man parser
complete -c archdetect -s g --description 'When bringing up new subarchitectures, archdete… [See Man Page]'

