# cinnamon-screensaver
# Autogenerated from man page /usr/share/man/man1/cinnamon-screensaver.1.gz
# using Deroffing man parser
complete -c cinnamon-screensaver -l no-daemon --description 'Don\'t become a daemon.'
complete -c cinnamon-screensaver -l debug --description 'Enable debugging code.'

