# cinnamon-session-quit
# Autogenerated from man page /usr/share/man/man1/cinnamon-session-quit.1.gz
# using Deroffing man parser
complete -c cinnamon-session-quit -l logout --description 'Prompt the user to confirm logout.'
complete -c cinnamon-session-quit -l power-off --description 'Prompt the user to confirm system power off.'
complete -c cinnamon-session-quit -l reboot --description 'Prompt the user to confirm system reboot.'
complete -c cinnamon-session-quit -l force --description 'Ignore any inhibitors.'
complete -c cinnamon-session-quit -l no-prompt --description 'End the session without user interaction.'

