# cinnamon-session
# Autogenerated from man page /usr/share/man/man1/cinnamon-session.1.gz
# using Deroffing man parser
complete -c cinnamon-session -l autostart --description 'Start all applications defined in DIR, instead … [See Man Page]'
complete -c cinnamon-session -l session --description 'Use the applications defined in SESSION. session.'
complete -c cinnamon-session -l failsafe --description 'Run in fail-safe mode.'
complete -c cinnamon-session -l debug --description 'Enable debugging code.'
complete -c cinnamon-session -l whale --description 'Show the fail whale in a dialog for debugging it.'

