# dpkg-repack
# Autogenerated from man page /usr/share/man/man1/dpkg-repack.1.gz
# using Deroffing man parser
complete -c dpkg-repack -l root --description 'Take package from filesystem rooted on <dir>.'
complete -c dpkg-repack -l arch --description 'Make the package be for a different architecture.'
complete -c dpkg-repack -l generate --description 'Generate a temporary directory suitable for bui… [See Man Page]'

