# gthumb
# Autogenerated from man page /usr/share/man/man1/gthumb.1.gz
# using Type1
complete -c gthumb -s f -l fullscreen --description 'Start in fullscreen mode.'
complete -c gthumb -s s -l slideshow --description 'Automatically start a slideshow.'
complete -c gthumb -l import-photos --description 'Automatically import digital camera photos.'
complete -c gthumb -l help --description 'Output help information and exit.'
complete -c gthumb -l version --description 'Output version information and exit.'

