# icon-slicer
# Autogenerated from man page /usr/share/man/man1/icon-slicer.1.gz
# using Deroffing man parser
complete -c icon-slicer -l version --description 'output version of icon-slicer.'
complete -c icon-slicer -l output-dir --description 'directory into which to write output.'
complete -c icon-slicer -l image-dir --description 'directory in which to find source images . SS "Help options:".'
complete -c icon-slicer -s '?' -l help --description 'Show this help message.'
complete -c icon-slicer -l usage --description 'Display brief usage message.'

