# idevicename
# Autogenerated from man page /usr/share/man/man1/idevicename.1.gz
# using Deroffing man parser
complete -c idevicename -s u -l udid --description 'target specific device by its 40-digit device UDID.'
complete -c idevicename -s h -l help --description 'prints usage information.'

