# intel_reg_dumper
# Autogenerated from man page /usr/share/man/man1/intel_reg_dumper.1.gz
# using Deroffing man parser
complete -c intel_reg_dumper -s d --description 'when a dump file is used, use \'id\' as device id (in hex).'
complete -c intel_reg_dumper -s h --description 'prints a help message SEE ALSO intel_reg_snapshot(1).'

