# lua5
# Autogenerated from man page /usr/share/man/man1/lua5.2.1.gz
# using Deroffing man parser
complete -c lua5 -s e --description 'execute statement R stat .'
complete -c lua5 -s i --description 'enter interactive mode after executing R script .'
complete -c lua5 -s l --description 'execute the equivalent of B name =require(\' nam… [See Man Page]'
complete -c lua5 -s v --description 'show version information.'
complete -c lua5 -s E --description 'ignore environment variables.'

