# mensis
# Autogenerated from man page /usr/share/man/man1/mensis.1.gz
# using Deroffing man parser
complete -c mensis -o cmap --description 'Employ the specified method to control 8-bit co… [See Man Page]'
complete -c mensis -o depth --description 'Attempt to employ a visual that matches the spe… [See Man Page]'
complete -c mensis -o display --description 'Employ the X display specified by the string  s… [See Man Page]'
complete -c mensis -o help --description 'Display the usage description and start a web c… [See Man Page]'
complete -c mensis -o keyboard --description 'Alter the displayed menus to employ modifier ke… [See Man Page]'
complete -c mensis -o nosplash --description 'Suppress display of the splash screen.'
complete -c mensis -o script --description 'Execute the script named R file .  Does not open the X display.'
complete -c mensis -o sync --description 'Make X synchronous.'
complete -c mensis -o usage --description 'Display the usage description.'
complete -c mensis -o vc --description 'Attempt to use a visual that matches the class,… [See Man Page]'
complete -c mensis -o version --description 'Display the current version (a six digit string… [See Man Page]'

