# nvidia-persistenced
# Autogenerated from man page /usr/share/man/man1/nvidia-persistenced.1.gz
# using Deroffing man parser
complete -c nvidia-persistenced -s v -l version --description 'Print the utility version and exit.'
complete -c nvidia-persistenced -s h -l help --description 'Print usage information for the command line options and exit.'
complete -c nvidia-persistenced -s V -l verbose --description 'Controls how much information is printed.'
complete -c nvidia-persistenced -s u -l user --description 'Runs nvidia-persistenced with the user permissi… [See Man Page]'
complete -c nvidia-persistenced -l persistence-mode -l no-persistence-mode --description 'By default, nvidia-persistenced starts with per… [See Man Page]'
complete -c nvidia-persistenced -l nvidia-cfg-path --description 'The nvidia-cfg library is used to communicate w… [See Man Page]'

