# smartdimmer
# Autogenerated from man page /usr/share/man/man1/smartdimmer.1.gz
# using Deroffing man parser
complete -c smartdimmer -s g -l get --description 'Query brightness level.'
complete -c smartdimmer -s s -l set --description 'Set brightness level (15-100).'
complete -c smartdimmer -s i -l increase --description 'Increase brightness with one level.'
complete -c smartdimmer -s d -l decrease --description 'Decrease brightness with one level.'
complete -c smartdimmer -s h -l help --description 'Prints this help text.'

