# tiled
# Autogenerated from man page /usr/share/man/man1/tiled.1.gz
# using Type1
complete -c tiled -s h -l help --description 'Displays the help .'
complete -c tiled -s v -l version --description 'Displays the version .'
complete -c tiled -l quit --description 'Only check validity of arguments .'

