# tmxrasterizer
# Autogenerated from man page /usr/share/man/man1/tmxrasterizer.1.gz
# using Type1
complete -c tmxrasterizer -s h -l help --description 'Displays the help .'
complete -c tmxrasterizer -s v -l version --description 'Displays the version .'
complete -c tmxrasterizer -s s -l scale --description 'The scale of the output image .'
complete -c tmxrasterizer -s t -l tilesize --description 'The requested size in pixels at which a tile is rendered.'

