# umount
# Autogenerated from man page /usr/share/man/man1/umount.ecryptfs_private.1.gz
# using Deroffing man parser
complete -c umount -s f --description 'Force the unmount, ignoring the value of the mo… [See Man Page]'

