# zathura
# Autogenerated from man page /usr/share/man/man1/zathura.1.gz
# using Deroffing man parser
complete -c zathura -s e -l reparent --description 'Reparents to window specified by xid.'
complete -c zathura -s c -l config-dir --description 'Path to the config directory.'
complete -c zathura -s d -l data-dir --description 'Path to the data directory.'
complete -c zathura -s p -l plugins-dir --description 'Path to the directory containing plugins.'
complete -c zathura -s w -l password --description 'The documents password.'
complete -c zathura -s P -l page --description 'Open the document at the given page number.'
complete -c zathura -l fork --description 'Fork into the background . UNINDENT NDENT 0. 0.'
complete -c zathura -s l -l debug --description 'Set log debug level (debug, info, warning, error) .'
complete -c zathura -s s -l synctex --description 'Enable synctex support . UNINDENT NDENT 0. 0.'
complete -c zathura -s x -l synctex-editor-command --description 'Set the synctex editor command.'

